### ISSUE TITLE
liver-top command doesn't work

### ISSUE THREAD

**Issue by 5ur3z** [Pandaria98/Seen#3]
[TaskExecutor/ERROR]: Error translate text "mcd_seen.fmt.liver_top" to language zh_cn, en_us

**Comment by Ra1ny-Yuki** [comment]
Try this
https://github.com/TISUnion/Seen/releases/tag/1.2.1-alpha.1

**Comment by 5ur3z** [comment]
感谢，终于好使了（
才发现是TIS团队做的😂
