### ISSUE TITLE
TypeError: seen_fmt_tr() got an unexapected keyword argument '_mcdr_tr_language'

### ISSUE THREAD

**Issue by GOOLDOVE** [Pandaria98/Seen#4]
Just now, I tried to run this plugin on MCDR, but the error was 
 `TypeError: see_ Fmt_ Tr() got an inexplicated keyword argument '_ MCDR_ TR_`
So I analyzed the source code and found the wrong one in interface.py
![image](https://github.com/TISUnion/Seen/assets/81006632/4ed9dace-302b-4007-9af6-7136f9943031)
![image](https://github.com/TISUnion/Seen/assets/81006632/f24c06b1-ee4e-474b-a16d-8051e1b3fc2b)

**Comment by Ra1ny-Yuki** [comment]
This should be fixed in the latest pre-release
